# Generated by Django 5.2.18 on 2026-10-07 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cabinet", "0065_remove_analystprofile_legacy_vip"),
        ("wallets", "0017_alter_capperrealbalance_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("cloudpayments", "CloudPayments (карта)"),
                            ("nowpayments", "NOWPayments (крипто)"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Провайдер",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("coin_package", "Пакет коинов"),
                            ("paid_subscription", "Платная подписка"),
                            ("vip_plan", "VIP-тариф"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Назначение",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создан"),
                            ("pending", "Ожидает оплаты"),
                            ("processing", "Обрабатывается"),
                            ("partially_paid", "Оплачен частично"),
                            ("succeeded", "Оплачен"),
                            ("failed", "Ошибка оплаты"),
                            ("canceled", "Отменён"),
                            ("expired", "Истёк"),
                            ("refunded", "Возвращён"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма к оплате"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=8, verbose_name="Валюта"
                    ),
                ),
                (
                    "amount_rub",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цена товара, ₽"
                    ),
                ),
                (
                    "product_snapshot",
                    models.JSONField(default=dict, verbose_name="Снимок товара"),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="ID платежа у провайдера",
                    ),
                ),
                (
                    "external_invoice_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="ID счёта у провайдера"
                    ),
                ),
                (
                    "checkout_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="Ссылка на оплату"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=24,
                        null=True,
                        verbose_name="Оплачено",
                    ),
                ),
                (
                    "paid_currency",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Валюта оплаты"
                    ),
                ),
                (
                    "is_test",
                    models.BooleanField(default=False, verbose_name="Тестовый платёж"),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Причина ошибки"
                    ),
                ),
                (
                    "provider_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Последний ответ провайдера",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Истекает"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Оплачен"),
                ),
                (
                    "fulfilled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Товар выдан"
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Возвращён"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "coin_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_payments",
                        to="wallets.coinpackage",
                        verbose_name="Пакет коинов",
                    ),
                ),
                (
                    "paid_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_payments",
                        to="cabinet.analystpaidplan",
                        verbose_name="Тариф подписки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "vip_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_payments",
                        to="cabinet.vipplan",
                        verbose_name="VIP-тариф",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="Провайдер"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=32, verbose_name="Тип события"),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        max_length=128, verbose_name="Ключ идемпотентности"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="ID у провайдера"
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="Данные")),
                (
                    "signature_valid",
                    models.BooleanField(default=False, verbose_name="Подпись верна"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Обработано"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Получено"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="payments.payment",
                        verbose_name="Платёж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие платежа",
                "verbose_name_plural": "События платежей",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="payment_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "created_at"], name="payment_user_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("provider", "external_id"),
                name="unique_payment_provider_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentevent",
            constraint=models.UniqueConstraint(
                fields=("provider", "dedup_key"), name="unique_payment_event_dedup"
            ),
        ),
    ]
