# Generated by Django 5.2.18 on 2026-10-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("cloudpayments", "CloudPayments (карта)"),
                    ("nowpayments", "NOWPayments (крипто)"),
                    ("telegram_stars", "Telegram Stars"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="Провайдер",
            ),
        ),
    ]
