# Generated by Django 5.2.17 on 2026-08-26 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reader', 'Пользователь'), ('expert', 'Эксперт')], db_index=True, max_length=16, verbose_name='Тип')),
                ('persona', models.CharField(blank=True, max_length=120, verbose_name='Персона')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
                'ordering': ('kind', 'user__username'),
            },
        ),
        migrations.CreateModel(
            name='BotActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('follow', 'Подписка'), ('unfollow', 'Отписка'), ('like', 'Лайк'), ('unlike', 'Снять лайк'), ('prediction', 'Прогноз')], db_index=True, max_length=24, verbose_name='Действие')),
                ('target', models.CharField(blank=True, max_length=160, verbose_name='Цель')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='bots.botaccount')),
            ],
            options={
                'verbose_name': 'Лог действия бота',
                'verbose_name_plural': 'Логи действий ботов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BotExpertStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence_days', models.PositiveSmallIntegerField(default=1, verbose_name='Периодичность дней')),
                ('daily_predictions_min', models.PositiveSmallIntegerField(default=1, verbose_name='Минимум прогнозов')),
                ('daily_predictions_max', models.PositiveSmallIntegerField(default=2, verbose_name='Максимум прогнозов')),
                ('market_preference', models.CharField(default='winner', max_length=40, verbose_name='Любимый рынок')),
                ('risk_profile', models.CharField(choices=[('safe', 'Осторожный'), ('balanced', 'Баланс'), ('aggressive', 'Агрессивный')], default='balanced', max_length=16, verbose_name='Риск')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Следующий запуск')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('bot', models.OneToOneField(limit_choices_to={'kind': 'expert'}, on_delete=django.db.models.deletion.CASCADE, related_name='expert_strategy', to='bots.botaccount', verbose_name='Бот-эксперт')),
            ],
            options={
                'verbose_name': 'Стратегия бота-эксперта',
                'verbose_name_plural': 'Стратегии ботов-экспертов',
                'ordering': ('next_run_at', 'bot__user__username'),
            },
        ),
    ]
