# Generated by Django 5.2.17 on 2026-09-05 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_remove_botexpertstrategy_market_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPlannedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('prediction', 'Прогноз'), ('reader_activity', 'Лайк/подписка'), ('tournament_activity', 'Турнир')], db_index=True, max_length=32, verbose_name='Действие')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('done', 'Выполнено'), ('skipped', 'Пропущено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Результат')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='Запланировано на')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_actions', to='bots.botaccount', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Запланированное действие бота',
                'verbose_name_plural': 'Запланированные действия ботов',
                'ordering': ('scheduled_at', 'id'),
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='botplan_status_due_idx'), models.Index(fields=['bot', 'action', 'status'], name='botplan_bot_action_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('bot__isnull', False)), fields=('bot', 'action'), name='unique_pending_bot_action'), models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('action', 'tournament_activity'), ('bot__isnull', True)), fields=('action',), name='unique_pending_tournament_action')],
            },
        ),
    ]
