# Generated by Django 5.2.17 on 2026-09-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_botplannedaction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='botplannedaction',
            name='unique_pending_bot_action',
        ),
        migrations.RemoveConstraint(
            model_name='botplannedaction',
            name='unique_pending_tournament_action',
        ),
        migrations.AddConstraint(
            model_name='botplannedaction',
            constraint=models.UniqueConstraint(condition=models.Q(('bot__isnull', False), ('status', 'pending')), fields=('bot', 'action'), name='unique_pending_bot_action'),
        ),
        migrations.AddConstraint(
            model_name='botplannedaction',
            constraint=models.UniqueConstraint(condition=models.Q(('action', 'tournament_activity'), ('bot__isnull', True), ('status', 'pending')), fields=('action',), name='unique_pending_tournament_action'),
        ),
    ]
