# Generated by Django 5.2.17 on 2026-09-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_remove_botplannedaction_unique_pending_bot_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotOnlineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='Начало')),
                ('ends_at', models.DateTimeField(db_index=True, verbose_name='Конец')),
                ('target_actions', models.PositiveSmallIntegerField(default=0, verbose_name='Цель действий')),
                ('actions_planned', models.PositiveSmallIntegerField(default=0, verbose_name='Запланировано действий')),
                ('actions_done', models.PositiveSmallIntegerField(default=0, verbose_name='Выполнено действий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_sessions', to='bots.botaccount', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Онлайн-сессия бота',
                'verbose_name_plural': 'Онлайн-сессии ботов',
                'ordering': ('-starts_at', '-id'),
                'indexes': [models.Index(fields=['starts_at', 'ends_at'], name='botsession_window_idx'), models.Index(fields=['bot', 'starts_at'], name='botsession_bot_start_idx')],
            },
        ),
    ]
