# Generated by Django 5.2.17 on 2026-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_botonlinesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRuntimeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('all', 'Все включено'), ('paused', 'Пауза'), ('presence_only', 'Только онлайн'), ('tournaments_only', 'Только турниры')], default='all', max_length=24, verbose_name='Режим')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Заметка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Управление ботами',
                'verbose_name_plural': 'Управление ботами',
            },
        ),
    ]
