# Generated by Django 5.2.17 on 2026-08-26 13:26

import tinymce.models
from django.db import migrations, models


def create_default_pages(apps, schema_editor):
    StaticPage = apps.get_model("front", "StaticPage")
    WebsiteSettings = apps.get_model("front", "WebsiteSettings")

    WebsiteSettings.objects.get_or_create(
        pk=1,
        defaults={
            "site_name": "КапперХаб",
            "fixed_tg_enable": False,
            "fixed_tg_title": "Бесплатный прогноз в Telegram",
        },
    )

    pages = [
        {
            "title": "Политика конфиденциальности",
            "slug": "privacy-policy",
            "footer_order": 10,
            "content": (
                "<p>На этой странице описывается, какие данные собирает сервис, "
                "для чего они используются и как пользователь может запросить "
                "изменение или удаление своих данных.</p>"
            ),
        },
        {
            "title": "Пользовательское соглашение",
            "slug": "terms",
            "footer_order": 20,
            "content": (
                "<p>Используя сайт, пользователь соглашается с правилами сервиса. "
                "Прогнозы публикуются в информационных целях и не являются гарантией результата.</p>"
            ),
        },
        {
            "title": "Политика cookies",
            "slug": "cookies",
            "footer_order": 30,
            "content": (
                "<p>Сайт может использовать cookies для авторизации, безопасности, "
                "аналитики и сохранения пользовательских настроек.</p>"
            ),
        },
        {
            "title": "Контакты",
            "slug": "contacts",
            "footer_order": 40,
            "content": (
                "<p>Связаться с администрацией можно через каналы, указанные на сайте "
                "или добавленные в настройках проекта.</p>"
            ),
        },
    ]
    for page in pages:
        StaticPage.objects.get_or_create(
            slug=page["slug"],
            defaults={
                "title": page["title"],
                "content": page["content"],
                "is_published": True,
                "show_in_footer": True,
                "footer_order": page["footer_order"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('content', tinymce.models.HTMLField(verbose_name='Содержание')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликована')),
                ('show_in_footer', models.BooleanField(db_index=True, default=True, verbose_name='Показывать в футере')),
                ('footer_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок в футере')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
                'ordering': ('footer_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='КапперХаб', max_length=120, verbose_name='Название сайта')),
                ('fixed_tg_enable', models.BooleanField(default=False, verbose_name='Показывать Telegram-баннер')),
                ('fixed_tg_link', models.URLField(blank=True, max_length=500, verbose_name='Ссылка Telegram')),
                ('fixed_tg_title', models.CharField(blank=True, default='Бесплатный прогноз в Telegram', max_length=120, verbose_name='Текст Telegram-баннера')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.RunPython(create_default_pages, migrations.RunPython.noop),
    ]
