# Generated by Django 5.2.17 on 2026-09-09 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_wikitermsection_wikiterm_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Категория статьи',
                'verbose_name_plural': 'Категории статей',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='is_main',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Главная статья'),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time_minutes',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Время чтения, мин'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, help_text='Через запятую', max_length=300, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='front.articlecategory', verbose_name='Категория'),
        ),
    ]
