# Generated by Django 5.2.17 on 2026-09-27 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_unique_main_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertRankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, max_length=16, verbose_name='Период')),
                ('sport_code', models.CharField(db_index=True, default='all', max_length=50, verbose_name='Вид спорта')),
                ('group', models.CharField(db_index=True, default='all', max_length=16, verbose_name='Группа')),
                ('roi_period_days', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Период ROI, дней')),
                ('entries_count', models.PositiveIntegerField(default=0, verbose_name='Записей')),
                ('built_at', models.DateTimeField(auto_now=True, verbose_name='Собран')),
            ],
            options={
                'verbose_name': 'Снимок рейтинга экспертов',
                'verbose_name_plural': 'Снимки рейтинга экспертов',
                'indexes': [models.Index(fields=['period', 'sport_code', 'group', 'roi_period_days'], name='exp_rank_snap_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('period', 'sport_code', 'group', 'roi_period_days'), name='uniq_exp_rank_snapshot', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='ExpertRankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(db_index=True, verbose_name='Место')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='Метрики')),
                ('ranking_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина рейтинга')),
                ('trust_index', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Индекс доверия')),
                ('ranking_score', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Рейтинговый балл')),
                ('author_roi', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='ROI отображения')),
                ('author_roi_all_time', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='ROI за всё время')),
                ('settled_count', models.PositiveIntegerField(default=0, verbose_name='Рассчитанных прогнозов')),
                ('roi_settled_count', models.PositiveIntegerField(default=0, verbose_name='Рассчитанных прогнозов ROI')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='Подписчиков')),
                ('publications_count', models.PositiveIntegerField(default=0, verbose_name='Публикаций')),
                ('wins_count', models.PositiveIntegerField(default=0, verbose_name='Выигрышей')),
                ('losses_count', models.PositiveIntegerField(default=0, verbose_name='Проигрышей')),
                ('sports_count', models.PositiveIntegerField(default=0, verbose_name='Видов спорта')),
                ('recent_publications_count', models.PositiveIntegerField(default=0, verbose_name='Публикаций за 30 дней')),
                ('last_publication_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя публикация')),
                ('is_vip_active', models.BooleanField(default=False, verbose_name='VIP активен')),
                ('vip_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='VIP до')),
                ('vip_subscription_activated_at', models.DateTimeField(blank=True, null=True, verbose_name='VIP активирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_ranking_entries', to=settings.AUTH_USER_MODEL, verbose_name='Аналитик')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='front.expertrankingsnapshot', verbose_name='Снимок')),
            ],
            options={
                'verbose_name': 'Запись рейтинга экспертов',
                'verbose_name_plural': 'Записи рейтинга экспертов',
                'ordering': ('snapshot', 'rank'),
                'indexes': [models.Index(fields=['snapshot', 'rank'], name='expert_rank_entry_rank_idx'), models.Index(fields=['analyst'], name='expert_rank_entry_analyst_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'analyst'), name='uniq_exp_rank_entry_analyst'), models.UniqueConstraint(fields=('snapshot', 'rank'), name='uniq_exp_rank_entry_rank')],
            },
        ),
    ]
