# Generated by Django 5.2.17 on 2026-09-27 11:25

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_expertrankingsnapshot_expertrankingentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Категория новости',
                'verbose_name_plural': 'Категории новостей',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=240, unique=True, verbose_name='Slug')),
                ('description', models.TextField(max_length=700, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='Изображение')),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=3, verbose_name='Время чтения, мин')),
                ('tags', models.CharField(blank=True, help_text='Через запятую', max_length=300, verbose_name='Теги')),
                ('is_main', models.BooleanField(db_index=True, default=False, verbose_name='Главная новость')),
                ('content', tinymce.models.HTMLField(verbose_name='Контент')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликована')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='front.newscategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('is_main',), name='unique_main_news')],
            },
        ),
    ]
