# Generated by Django 5.2.17 on 2026-09-08 23:24

import shutil
from pathlib import Path

from django.conf import settings
from django.db import migrations, models


PROMO_BANNER_ROUTES = (
    ("Главная", "front:index"),
    ("Стать каппером", "cabinet:become_capper"),
    ("Как пользоваться", "front:how_it_works"),
    ("Статистика экспертов", "front:cappers_stats"),
)


def seed_main_promo_banner(apps, schema_editor):
    PromoBanner = apps.get_model("pages", "PromoBanner")
    PageSEO = apps.get_model("pages", "PageSEO")

    source = Path(settings.BASE_DIR) / "front/static/front/img/main_banner_main_page.png"
    target_name = "promo_banners/main_banner_main_page.png"
    target = Path(settings.MEDIA_ROOT) / target_name
    if source.exists() and not target.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)

    banner, _ = PromoBanner.objects.update_or_create(
        name="Главный турнирный баннер",
        defaults={
            "eyebrow": "Турниры",
            "title": "Участвуй\nв турнирах",
            "text": "Покажи свои знания, поднимайся в рейтинге и выигрывай призы.",
            "button_label": "Все турниры",
            "button_url": "/tournaments/",
            "image": target_name,
            "title_color": "#050505",
            "text_color": "rgba(0, 0, 0, .76)",
            "button_color": "#151719",
            "button_text_color": "#fff200",
            "is_active": True,
        },
    )

    for name, route_name in PROMO_BANNER_ROUTES:
        page, _ = PageSEO.objects.get_or_create(
            route_name=route_name,
            exact_path="",
            defaults={
                "name": name,
                "is_active": True,
            },
        )
        page.promo_banners.add(banner)


def remove_main_promo_banner(apps, schema_editor):
    PromoBanner = apps.get_model("pages", "PromoBanner")
    PromoBanner.objects.filter(name="Главный турнирный баннер").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_help_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название в админке')),
                ('eyebrow', models.CharField(blank=True, max_length=80, verbose_name='Метка')),
                ('title', models.CharField(max_length=180, verbose_name='Title')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('button_label', models.CharField(max_length=80, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(help_text='Можно указать относительный путь, например /tournaments/, или полный URL.', max_length=1000, verbose_name='Ссылка кнопки')),
                ('image', models.ImageField(upload_to='promo_banners/', verbose_name='Изображение')),
                ('mobile_image', models.ImageField(blank=True, help_text='Если заполнено, используется на экранах до 767 px.', upload_to='promo_banners/mobile/', verbose_name='Мобильное изображение')),
                ('title_color', models.CharField(default='#050505', max_length=32, verbose_name='Цвет title')),
                ('text_color', models.CharField(default='rgba(0, 0, 0, .76)', max_length=32, verbose_name='Цвет текста')),
                ('button_color', models.CharField(default='#151719', max_length=32, verbose_name='Цвет кнопки')),
                ('button_text_color', models.CharField(default='#fff200', max_length=32, verbose_name='Цвет текста кнопки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показывать')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Промо-баннер',
                'verbose_name_plural': 'Промо-баннеры',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='pageseo',
            name='promo_banners',
            field=models.ManyToManyField(blank=True, related_name='pages', to='pages.promobanner', verbose_name='Промо-баннеры'),
        ),
        migrations.RunPython(seed_main_promo_banner, remove_main_promo_banner),
    ]
