# Generated by Django 5.2.17 on 2026-09-01 13:50

import django.db.models.deletion
import django.utils.timezone
import tournaments.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0019_predictioncoupon_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название турнира')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('rules_text', models.TextField(blank=True, verbose_name='Условия турнира')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'Архив')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('starts_at', models.DateTimeField(verbose_name='Дата начала')),
                ('ends_at', models.DateTimeField(verbose_name='Дата окончания')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to=tournaments.models.tournament_image_upload_path, verbose_name='Изображение карточки')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=tournaments.models.tournament_image_upload_path, verbose_name='Главное изображение')),
                ('prize_first', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Приз за 1 место')),
                ('prize_second', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Приз за 2 место')),
                ('prize_third', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Приз за 3 место')),
                ('min_coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.01'), max_digits=8, verbose_name='Минимальный коэффициент')),
                ('min_confidence', models.PositiveSmallIntegerField(default=0, verbose_name='Минимальная уверенность, %')),
                ('coupon_type_rule', models.CharField(choices=[('any', 'Любой'), ('single', 'Только одиночные'), ('express', 'Только экспрессы')], default='any', max_length=16, verbose_name='Тип прогноза')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Показывать выше остальных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('allowed_sports', models.ManyToManyField(blank=True, help_text='Если пусто, доступны все виды спорта.', related_name='tournaments', to='game.sport', verbose_name='Разрешённые виды спорта')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ('-is_featured', '-starts_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TournamentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=tournaments.models.tournament_achievement_icon_upload_path, verbose_name='Иконка достижения')),
                ('kind', models.CharField(choices=[('first_place', '1 место'), ('second_place', '2 место'), ('third_place', '3 место'), ('participation', 'Участие'), ('custom', 'Другое')], default='custom', max_length=24, verbose_name='Тип')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Достижение турнира',
                'verbose_name_plural': 'Достижения турниров',
                'ordering': ('tournament', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Участвует'), ('left', 'Вышел'), ('disqualified', 'Дисквалифицирован')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подключения')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament', verbose_name='Турнир')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL, verbose_name='Каппер')),
            ],
            options={
                'verbose_name': 'Участник турнира',
                'verbose_name_plural': 'Участники турниров',
                'ordering': ('-joined_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TournamentCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_link', to='game.predictioncoupon', verbose_name='Прогноз')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_coupons', to='tournaments.tournament', verbose_name='Турнир')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_coupons', to='tournaments.tournamentparticipant', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Прогноз турнира',
                'verbose_name_plural': 'Прогнозы турниров',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TournamentPredictionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_prediction_entries', to='game.match', verbose_name='Матч')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_entries', to='tournaments.tournamentparticipant', verbose_name='Участник')),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entry', to='game.prediction', verbose_name='Позиция прогноза')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_entries', to='tournaments.tournament', verbose_name='Турнир')),
                ('tournament_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_entries', to='tournaments.tournamentcoupon', verbose_name='Турнирный прогноз')),
            ],
            options={
                'verbose_name': 'Позиция прогноза турнира',
                'verbose_name_plural': 'Позиции прогнозов турниров',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='Место')),
                ('coupons_count', models.PositiveIntegerField(default=0, verbose_name='Прогнозов')),
                ('wins_count', models.PositiveIntegerField(default=0, verbose_name='Выигрышей')),
                ('losses_count', models.PositiveIntegerField(default=0, verbose_name='Проигрышей')),
                ('refunds_count', models.PositiveIntegerField(default=0, verbose_name='Возвратов')),
                ('pending_count', models.PositiveIntegerField(default=0, verbose_name='Ожидают расчёта')),
                ('total_stake', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма ставок')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Прибыль')),
                ('roi_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ROI, %')),
                ('prize_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Приз')),
                ('finalized_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Зафиксирован')),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='tournaments.tournamentachievement', verbose_name='Достижение')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tournaments.tournamentparticipant', verbose_name='Участник')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Итог турнира',
                'verbose_name_plural': 'Итоги турниров',
                'ordering': ('tournament', 'rank'),
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='tournaments_status_00f2de_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['is_featured', 'starts_at'], name='tournaments_is_feat_26b0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament', 'status', 'joined_at'], name='tournaments_tournam_cea605_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['user', 'status', 'joined_at'], name='tournaments_user_id_89ccb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentparticipant',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='unique_tournament_participant'),
        ),
        migrations.AddIndex(
            model_name='tournamentcoupon',
            index=models.Index(fields=['tournament', 'created_at'], name='tournaments_tournam_f9f9d8_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentcoupon',
            index=models.Index(fields=['participant', 'created_at'], name='tournaments_partici_2b1e98_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentpredictionentry',
            index=models.Index(fields=['tournament', 'match'], name='tournaments_tournam_00bf36_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentpredictionentry',
            index=models.Index(fields=['participant', 'match'], name='tournaments_partici_2d291f_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentpredictionentry',
            constraint=models.UniqueConstraint(fields=('tournament', 'participant', 'match'), name='unique_tournament_participant_match'),
        ),
        migrations.AddConstraint(
            model_name='tournamentresult',
            constraint=models.UniqueConstraint(fields=('tournament', 'participant'), name='unique_tournament_result_participant'),
        ),
        migrations.AddConstraint(
            model_name='tournamentresult',
            constraint=models.UniqueConstraint(fields=('tournament', 'rank'), name='unique_tournament_result_rank'),
        ),
        migrations.AddConstraint(
            model_name='tournamentresult',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='tournament_result_rank_positive'),
        ),
    ]
