# Generated by Django 5.2.17 on 2026-09-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='min_confidence',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Оставьте пустым или укажите 0, если уверенность не участвует в условиях турнира.', null=True, verbose_name='Минимальная уверенность, %'),
        ),
    ]
