# Generated by Django 5.2.17 on 2026-10-04 12:03

import django.db.models.deletion
import tournaments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_country_sport_local_media'),
        ('tournaments', '0002_alter_tournament_min_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='eligibility_sport',
            field=models.ForeignKey(blank=True, help_text='Если выбран, прогнозы и победы для допуска считаются только по этому спорту.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_tournaments', to='game.sport', verbose_name='Спорт для проверки активности'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format_rules_text',
            field=models.TextField(blank=True, default='', help_text='Каждая строка показывается отдельным пунктом в блоке «Формат турнира».', verbose_name='Формат турнира на странице'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='hero_icon',
            field=models.ImageField(blank=True, help_text='Показывается в hero на внутренней странице турнира.', null=True, upload_to=tournaments.models.tournament_image_upload_path, verbose_name='Иконка турнира'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_user_predictions',
            field=models.PositiveIntegerField(default=0, help_text='0 — не проверять.', verbose_name='Мин. опубликованных прогнозов для участия'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_user_wins',
            field=models.PositiveIntegerField(default=0, help_text='0 — не проверять.', verbose_name='Мин. выигранных прогнозов для участия'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participation_rules_text',
            field=models.TextField(blank=True, default='', help_text='Каждая строка показывается отдельным пунктом в блоке «Условия участия».', verbose_name='Условия участия на странице'),
        ),
    ]
