# Generated by Django 5.2.17 on 2026-10-04 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_eligibility_sport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('period', models.CharField(blank=True, max_length=120, verbose_name='Период')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Этап турнира',
                'verbose_name_plural': 'Этапы турниров',
                'ordering': ('tournament', 'sort_order', 'id'),
                'indexes': [models.Index(fields=['tournament', 'is_active', 'sort_order'], name='tournaments_tournam_20a8de_idx')],
            },
        ),
    ]
