# Generated by Django 5.2.17 on 2026-10-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournamentstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(verbose_name='Место')),
                ('money_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Денежный приз')),
                ('coins_amount', models.PositiveIntegerField(default=0, help_text='Дополнительные коины на виртуальный счет.', verbose_name='Коины')),
                ('vip_days', models.PositiveIntegerField(default=0, help_text='Сколько дней VIP выдать вместе с призом.', verbose_name='VIP, дней')),
                ('title', models.CharField(blank=True, help_text='Например: VIP на 3 месяца, бонус коинов, специальный статус.', max_length=140, verbose_name='Название награды')),
                ('description', models.TextField(blank=True, verbose_name='Описание награды')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='tournaments.tournamentachievement', verbose_name='Достижение')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Приз турнира',
                'verbose_name_plural': 'Призы турниров',
                'ordering': ('tournament', 'sort_order', 'place', 'id'),
                'indexes': [models.Index(fields=['tournament', 'is_active', 'sort_order', 'place'], name='tournaments_tournam_2ade90_idx')],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'place'), name='unique_tournament_prize_place')],
            },
        ),
    ]
