# Generated by Django 5.2.17 on 2026-10-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_migrate_legacy_prizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='access_type',
            field=models.CharField(choices=[('open', 'Открытый'), ('closed', 'Закрытый')], db_index=True, default='open', max_length=16, verbose_name='Тип доступа'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='analysts_only',
            field=models.BooleanField(default=True, help_text='Если включено, участвовать могут только пользователи со статусом каппера.', verbose_name='Только капперы'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='entry_fee_coins',
            field=models.PositiveIntegerField(default=0, help_text='Используется для платных турниров.', verbose_name='Стоимость участия, коины'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='entry_type',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('paid', 'Платный')], db_index=True, default='free', max_length=16, verbose_name='Тип участия'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='new_users_only',
            field=models.BooleanField(default=False, verbose_name='Только новые пользователи'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='vip_only',
            field=models.BooleanField(default=False, verbose_name='Только VIP'),
        ),
    ]
