# Generated by Django 5.2.17 on 2026-10-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_country_sport_local_media'),
        ('tournaments', '0007_tournament_access_type_tournament_analysts_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='eligibility_mode',
            field=models.CharField(choices=[('all', 'Все условия'), ('any', 'Любое условие')], default='all', help_text='Все активные условия обязательны или достаточно любого одного.', max_length=16, verbose_name='Логика условий допуска'),
        ),
        migrations.CreateModel(
            name='TournamentEligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('vip_status', 'VIP-статус'), ('new_user', 'Новый пользователь'), ('tournament_wins', 'Победы в турнирах'), ('predictions_count', 'Опубликованные прогнозы'), ('winning_predictions_count', 'Выигранные прогнозы'), ('followers_count', 'Подписчики'), ('likes_count', 'Лайки'), ('live_predictions_count', 'Live-прогнозы'), ('custom_metric', 'Другая метрика')], max_length=40, verbose_name='Тип условия')),
                ('operator', models.CharField(choices=[('gte', 'Больше или равно'), ('lte', 'Меньше или равно'), ('eq', 'Равно')], default='gte', max_length=8, verbose_name='Оператор')),
                ('value', models.PositiveIntegerField(default=1, verbose_name='Значение')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Название условия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('sport', models.ForeignKey(blank=True, help_text='Если выбран, условие считается только по этому виду спорта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_eligibility_rules', to='game.sport', verbose_name='Спорт')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Условие допуска к турниру',
                'verbose_name_plural': 'Условия допуска к турнирам',
                'ordering': ('tournament', 'sort_order', 'id'),
                'indexes': [models.Index(fields=['tournament', 'is_active', 'sort_order'], name='tournaments_tournam_43adce_idx'), models.Index(fields=['rule_type', 'is_active'], name='tournaments_rule_ty_30e11d_idx')],
            },
        ),
    ]
