# Generated by Django 5.2.17 on 2026-10-05 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournament_eligibility_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPrizeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выдано денег')),
                ('coins_awarded', models.PositiveIntegerField(default=0, verbose_name='Выдано коинов')),
                ('vip_days_awarded', models.PositiveIntegerField(default=0, verbose_name='Выдано VIP-дней')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдано')),
                ('achievement_awarded', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prize_awards', to='tournaments.tournamentachievement', verbose_name='Выданное достижение')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_awards', to='tournaments.tournamentparticipant', verbose_name='Участник')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='tournaments.tournamentprize', verbose_name='Приз')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_awards', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Выдача приза турнира',
                'verbose_name_plural': 'Выдачи призов турниров',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tournament', 'created_at'], name='tournaments_tournam_c20a6b_idx'), models.Index(fields=['participant', 'created_at'], name='tournaments_partici_a6340a_idx')],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'participant'), name='unique_tournament_prize_award_participant')],
            },
        ),
    ]
