# Generated by Django 5.2.17 on 2026-10-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournamentprizeaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='reward_coins_wallet_text',
            field=models.CharField(blank=True, default='', help_text='Текст для призовых коинов во вкладке «Призы».', max_length=255, verbose_name='Куда начисляются коины'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='reward_payout_text',
            field=models.CharField(blank=True, default='', help_text='Текст для нижнего блока вкладки «Призы».', max_length=255, verbose_name='Срок выплаты призов'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='reward_rules_text',
            field=models.CharField(blank=True, default='', help_text='Текст условий попадания в призовую зону.', max_length=255, verbose_name='Условия призовой зоны'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='reward_wallet_text',
            field=models.CharField(blank=True, default='', help_text='Текст для денежного приза во вкладке «Призы».', max_length=255, verbose_name='Куда начисляются деньги'),
        ),
    ]
