# Generated by Django 5.2.18 on 2026-10-07 10:14

from django.db import migrations, models
from django.db.models import Max


def mark_tournaments_with_results_finalized(apps, schema_editor):
    # Results fixed before this field existed must not be fixed (and paid) again.
    Tournament = apps.get_model("tournaments", "Tournament")
    for tournament in Tournament.objects.filter(results__isnull=False).annotate(
        last_result_at=Max("results__finalized_at"),
    ):
        Tournament.objects.filter(pk=tournament.pk).update(finalized_at=tournament.last_result_at)


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0012_tournamentfaq"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="finalized_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Итоги фиксируются один раз: таблица замораживается, призы выдаются.",
                null=True,
                verbose_name="Итоги зафиксированы",
            ),
        ),
        migrations.RunPython(mark_tournaments_with_results_finalized, migrations.RunPython.noop),
    ]
