# Generated by Django 5.2.17 on 2026-08-30 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_simplify_bookmaker_placements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='match_bookmaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='back.bookmaker', verbose_name='Матч — БК'),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='prediction_bookmaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='back.bookmaker', verbose_name='Прогнозы — БК'),
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(blank=True, max_length=120, verbose_name='Промокод')),
                ('short_description', models.CharField(max_length=220, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('link', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='back.bookmaker', verbose_name='Букмекер')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
                'ordering': ('order', 'id'),
            },
        ),
    ]
