# Generated by Django 5.2.18 on 2026-10-07 13:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back", "0012_websitesettings_robots_txt"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="income_hold_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Доход каппера с подписок и реферальные начисления с оплат становятся доступны к выводу через столько дней: на случай возврата платежа. 0 — сразу.",
                verbose_name="Холд дохода с оплат, дней",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="min_withdrawal_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("500.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Минимальная сумма вывода, ₽",
            ),
        ),
    ]
