# Generated by Django 5.2.18 on 2026-10-07 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back", "0013_websitesettings_income_hold_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="referral_income_days",
            field=models.PositiveIntegerField(
                default=365,
                help_text="Сколько дней после регистрации приглашённого реферер получает процент. 0 — без ограничения.",
                verbose_name="Срок реферального дохода, дней",
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="referral_subscription_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Процент от комиссии площадки с подписки, а не от её полной цены.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Реферал — покупка подписки, %",
            ),
        ),
    ]
