# Generated by Django 5.2.18 on 2026-10-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back", "0015_footer_about_rules_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmaker",
            name="slider_img",
            field=models.ImageField(
                blank=True,
                upload_to="bookmakers/slider/",
                verbose_name="Фон карточки в мобильном слайдере",
            ),
        ),
    ]
