# Generated by Django 5.2.17 on 2026-08-30 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapperBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Баланс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capper_balance', to=settings.AUTH_USER_MODEL, verbose_name='Каппер')),
            ],
            options={
                'verbose_name': 'Баланс каппера',
                'verbose_name_plural': 'Балансы капперов',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('initial_bonus', 'Стартовый баланс'), ('virtual_deposit', 'Виртуальное пополнение'), ('prediction_stake', 'Списание за прогноз'), ('prediction_payout', 'Выплата по прогнозу'), ('prediction_refund', 'Возврат прогноза'), ('adjustment', 'Корректировка')], db_index=True, max_length=32, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Баланс после операции')),
                ('related_model', models.CharField(blank=True, max_length=100, verbose_name='Связанная модель')),
                ('related_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Связанный объект')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Каппер')),
            ],
            options={
                'verbose_name': 'Транзакция баланса',
                'verbose_name_plural': 'Транзакции баланса',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='wallets_bal_user_id_c9db1b_idx'), models.Index(fields=['related_model', 'related_id'], name='wallets_bal_related_288ad8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('related_id__isnull', False)), fields=('user', 'kind', 'related_model', 'related_id'), name='unique_balance_transaction_subject')],
            },
        ),
    ]
