# Generated by Django 5.2.17 on 2026-09-01 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_predictioncoupon_is_paid'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capperbalance',
            options={'ordering': ['user_id'], 'verbose_name': 'Виртуальный баланс пользователя', 'verbose_name_plural': 'Виртуальные балансы пользователей'},
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='kind',
            field=models.CharField(choices=[('initial_bonus', 'Стартовый баланс'), ('virtual_deposit', 'Виртуальное пополнение'), ('real_to_virtual', 'Перевод с реального баланса'), ('prediction_stake', 'Списание за прогноз'), ('prediction_payout', 'Выплата по прогнозу'), ('prediction_refund', 'Возврат прогноза'), ('copybet_stake', 'Списание за копиставку'), ('copybet_payout', 'Выплата по копиставке'), ('copybet_refund', 'Возврат копиставки'), ('adjustment', 'Корректировка')], db_index=True, max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='capperbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Виртуальный баланс'),
        ),
        migrations.AlterField(
            model_name='capperbalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capper_balance', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='CapperRealBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Реальный баланс')),
                ('pending_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ожидает вывода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_balance', to=settings.AUTH_USER_MODEL, verbose_name='Каппер')),
            ],
            options={
                'verbose_name': 'Реальный баланс каппера',
                'verbose_name_plural': 'Реальные балансы капперов',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='CopyBettingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('stopped', 'Остановлено')], db_index=True, default='active', max_length=16, verbose_name='Статус')),
                ('bank_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Банк для копирования')),
                ('stake_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент от банка на ставку')),
                ('stop_loss_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоп-лосс')),
                ('max_single_stake', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Максимум на одну ставку')),
                ('current_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Текущая просадка')),
                ('total_staked', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма ставок')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Чистая прибыль')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Запущено')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='Остановлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copybetting_followers', to=settings.AUTH_USER_MODEL, verbose_name='Каппер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copybetting_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка копибеттинга',
                'verbose_name_plural': 'Настройки копибеттинга',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CopiedBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_status', models.CharField(choices=[('pending', 'В ожидании'), ('win', 'Выигрыш'), ('lose', 'Проигрыш'), ('refund', 'Возврат')], db_index=True, default='pending', max_length=16, verbose_name='Результат')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('possible_payout', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Возможный выигрыш')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Прибыль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассчитана')),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_copied_bets', to=settings.AUTH_USER_MODEL, verbose_name='Каппер')),
                ('source_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_bets', to='game.predictioncoupon', verbose_name='Исходный прогноз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_bets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_bets', to='wallets.copybettingsubscription', verbose_name='Настройка копирования')),
            ],
            options={
                'verbose_name': 'Скопированная ставка',
                'verbose_name_plural': 'Скопированные ставки',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RealBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('subscription_income', 'Доход с подписки'), ('tournament_prize', 'Приз турнира'), ('real_deposit', 'Реальное пополнение'), ('virtual_top_up', 'Пополнение виртуального баланса'), ('withdrawal_request', 'Заявка на вывод'), ('withdrawal_cancel', 'Отмена вывода'), ('adjustment', 'Корректировка')], db_index=True, max_length=32, verbose_name='Тип')),
                ('status', models.CharField(choices=[('completed', 'Завершена'), ('pending', 'Ожидает'), ('canceled', 'Отменена')], db_index=True, default='completed', max_length=16, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Баланс после операции')),
                ('related_model', models.CharField(blank=True, max_length=100, verbose_name='Связанная модель')),
                ('related_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Связанный объект')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_balance_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Каппер')),
            ],
            options={
                'verbose_name': 'Транзакция реального баланса',
                'verbose_name_plural': 'Транзакции реального баланса',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='copybettingsubscription',
            index=models.Index(fields=['analyst', 'status', 'started_at'], name='wallets_cop_analyst_74ec68_idx'),
        ),
        migrations.AddIndex(
            model_name='copybettingsubscription',
            index=models.Index(fields=['user', 'status', 'started_at'], name='wallets_cop_user_id_77e299_idx'),
        ),
        migrations.AddConstraint(
            model_name='copybettingsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'analyst'), name='unique_copybetting_user_analyst'),
        ),
        migrations.AddConstraint(
            model_name='copybettingsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('bank_amount__gt', 0)), name='copybetting_bank_positive'),
        ),
        migrations.AddConstraint(
            model_name='copybettingsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('stake_percent__gt', 0)), name='copybetting_stake_percent_positive'),
        ),
        migrations.AddConstraint(
            model_name='copybettingsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('stake_percent__lte', 100)), name='copybetting_stake_percent_max'),
        ),
        migrations.AddConstraint(
            model_name='copybettingsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('stop_loss_amount__gte', 0)), name='copybetting_stop_loss_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='copybettingsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('max_single_stake__gte', 0)), name='copybetting_max_stake_non_negative'),
        ),
        migrations.AddIndex(
            model_name='copiedbet',
            index=models.Index(fields=['user', 'state_status', 'created_at'], name='wallets_cop_user_id_ffeec6_idx'),
        ),
        migrations.AddIndex(
            model_name='copiedbet',
            index=models.Index(fields=['analyst', 'created_at'], name='wallets_cop_analyst_e8c4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='copiedbet',
            index=models.Index(fields=['source_coupon', 'state_status'], name='wallets_cop_source__09b364_idx'),
        ),
        migrations.AddConstraint(
            model_name='copiedbet',
            constraint=models.UniqueConstraint(fields=('user', 'source_coupon'), name='unique_user_source_copied_bet'),
        ),
        migrations.AddConstraint(
            model_name='copiedbet',
            constraint=models.CheckConstraint(condition=models.Q(('stake__gt', 0)), name='copied_bet_stake_positive'),
        ),
        migrations.AddIndex(
            model_name='realbalancetransaction',
            index=models.Index(fields=['user', 'created_at'], name='wallets_rea_user_id_27bb27_idx'),
        ),
        migrations.AddIndex(
            model_name='realbalancetransaction',
            index=models.Index(fields=['related_model', 'related_id'], name='wallets_rea_related_f7e368_idx'),
        ),
        migrations.AddConstraint(
            model_name='realbalancetransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('related_id__isnull', False)), fields=('user', 'kind', 'related_model', 'related_id'), name='unique_real_balance_transaction_subject'),
        ),
    ]
