# Generated by Django 5.2.17 on 2026-09-01 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_predictioncoupon_is_paid'),
        ('wallets', '0002_alter_capperbalance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='copybettingsubscription',
            name='allowed_sports',
            field=models.ManyToManyField(blank=True, help_text='Если пусто, копируются все виды спорта.', related_name='copybetting_subscriptions', to='game.sport', verbose_name='Виды спорта для копирования'),
        ),
        migrations.AddField(
            model_name='copybettingsubscription',
            name='copy_regular_coupons',
            field=models.BooleanField(default=True, verbose_name='Копировать обычные прогнозы'),
        ),
        migrations.AddField(
            model_name='copybettingsubscription',
            name='copy_tournament_coupons',
            field=models.BooleanField(default=True, verbose_name='Копировать турнирные прогнозы'),
        ),
        migrations.AddField(
            model_name='copybettingsubscription',
            name='min_total_coefficient',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Минимальный общий коэффициент'),
        ),
        migrations.AlterField(
            model_name='copybettingsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('paused', 'На паузе'), ('stopped', 'Остановлено')], db_index=True, default='active', max_length=16, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='copybettingsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('min_total_coefficient__gte', 0)), name='copybetting_min_coefficient_non_negative'),
        ),
    ]
