# Generated by Django 5.2.17 on 2026-09-03 20:08

from django.db import migrations, models


def fill_active_since(apps, schema_editor):
    subscription_model = apps.get_model("wallets", "CopyBettingSubscription")
    subscription_model.objects.filter(active_since__isnull=True).update(active_since=models.F("started_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_capperbankstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='copybettingsubscription',
            name='active_since',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Активно с'),
        ),
        migrations.AddField(
            model_name='copybettingsubscription',
            name='pending_status',
            field=models.CharField(blank=True, choices=[('active', 'Активно'), ('paused', 'На паузе'), ('stopped', 'Остановлено')], db_index=True, default='', max_length=16, verbose_name='Запрошенный статус'),
        ),
        migrations.AddField(
            model_name='copybettingsubscription',
            name='pending_status_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запрошен статус'),
        ),
        migrations.RunPython(fill_active_since, migrations.RunPython.noop),
    ]
