# Generated by Django 5.2.17 on 2026-09-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_fix_legacy_rub_coin_cutover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realbalancetransaction',
            name='kind',
            field=models.CharField(choices=[('subscription_income', 'Доход с подписки'), ('tournament_prize', 'Приз турнира'), ('vip_purchase', 'Покупка VIP'), ('paid_prediction_purchase', 'Покупка платной подписки'), ('referral_subscription', 'Реферал: покупка подписки'), ('referral_tournament', 'Реферал: приз турнира'), ('referral_balance_top_up', 'Реферал: пополнение баланса'), ('real_deposit', 'Реальное пополнение'), ('withdrawal_request', 'Заявка на вывод'), ('withdrawal_cancel', 'Отмена вывода'), ('adjustment', 'Корректировка')], db_index=True, max_length=32, verbose_name='Тип'),
        ),
    ]
