# Generated by Django 5.2.17 on 2026-10-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_alter_realbalancetransaction_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='kind',
            field=models.CharField(choices=[('initial_grant', 'Стартовые коины'), ('package_purchase', 'Покупка пакета'), ('roulette_reward', 'Приз рулетки'), ('prediction_stake', 'Списание за прогноз'), ('prediction_payout', 'Выплата по прогнозу'), ('prediction_refund', 'Возврат прогноза'), ('copybet_stake', 'Списание за копиставку'), ('copybet_payout', 'Выплата по копиставке'), ('copybet_refund', 'Возврат копиставки'), ('daily_task_reward', 'Ежедневное задание'), ('tournament_entry_fee', 'Вход в турнир'), ('adjustment', 'Корректировка')], db_index=True, max_length=32, verbose_name='Тип'),
        ),
    ]
