# Generated by Django 5.2.18 on 2026-10-06 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0030_country_sport_local_media"),
        ("wallets", "0013_alter_cointransaction_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copiedbet",
            name="source_coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="copied_bets",
                to="game.predictioncoupon",
                verbose_name="Исходный прогноз",
            ),
        ),
    ]
