# Generated by Django 5.2.18 on 2026-10-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0014_copiedbet_source_coupon_restrict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cointransaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("initial_grant", "Стартовые коины"),
                    ("package_purchase", "Покупка пакета"),
                    ("roulette_reward", "Приз рулетки"),
                    ("prediction_stake", "Списание за прогноз"),
                    ("prediction_payout", "Выплата по прогнозу"),
                    ("prediction_refund", "Возврат прогноза"),
                    ("prediction_payout_reversal", "Сторно выплаты по прогнозу"),
                    ("copybet_stake", "Списание за копиставку"),
                    ("copybet_payout", "Выплата по копиставке"),
                    ("copybet_refund", "Возврат копиставки"),
                    ("copybet_payout_reversal", "Сторно выплаты по копиставке"),
                    ("daily_task_reward", "Ежедневное задание"),
                    ("tournament_entry_fee", "Вход в турнир"),
                    ("tournament_prize_coins", "Приз турнира"),
                    ("adjustment", "Корректировка"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="Тип",
            ),
        ),
    ]
