# Generated by Django 5.2.18 on 2026-10-07 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0015_alter_cointransaction_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="capperrealbalance",
            name="held",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Доход с оплат, который ещё нельзя вывести.",
                max_digits=12,
                verbose_name="В холде",
            ),
        ),
        migrations.AddField(
            model_name="realbalancetransaction",
            name="available_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Доступно с"
            ),
        ),
        migrations.AddField(
            model_name="realbalancetransaction",
            name="payout_details",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Реквизиты для вывода"
            ),
        ),
        migrations.AddField(
            model_name="realbalancetransaction",
            name="payout_reference",
            field=models.CharField(
                blank=True,
                help_text="Номер платёжного поручения или перевода. Нужен для подтверждения заявки.",
                max_length=100,
                verbose_name="Номер выплаты",
            ),
        ),
        migrations.AddField(
            model_name="realbalancetransaction",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Обработана"
            ),
        ),
        migrations.AddField(
            model_name="realbalancetransaction",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обработал",
            ),
        ),
        migrations.AlterField(
            model_name="realbalancetransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Завершена"),
                    ("pending", "Ожидает"),
                    ("canceled", "Отменена"),
                    ("held", "В холде"),
                ],
                db_index=True,
                default="completed",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
    ]
