# Generated by Django 5.2.18 on 2026-10-07 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0016_capperrealbalance_held_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="capperrealbalance",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="real_balance",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Каппер",
            ),
        ),
        migrations.AlterField(
            model_name="cointransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coin_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="coinwallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coin_wallet",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="copiedbet",
            name="analyst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_copied_bets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Каппер",
            ),
        ),
        migrations.AlterField(
            model_name="copiedbet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="copied_bets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="realbalancetransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="real_balance_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Каппер",
            ),
        ),
    ]
