# Generated by Django 5.2.17 on 2026-08-25 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('neurokeff', 'Neurokeff')], default='neurokeff', max_length=32)),
                ('external_id', models.PositiveBigIntegerField()),
                ('sport_id', models.PositiveIntegerField(default=2)),
                ('sync_scope', models.CharField(choices=[('live', 'Live'), ('prematch', 'Prematch'), ('finished', 'Finished')], max_length=16)),
                ('time_status', models.CharField(blank=True, max_length=8)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('league_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('league_name', models.CharField(blank=True, max_length=255)),
                ('league_country', models.CharField(blank=True, max_length=120)),
                ('home_team_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('home_team_name', models.CharField(blank=True, max_length=255)),
                ('home_team_logo', models.URLField(blank=True, max_length=500)),
                ('away_team_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('away_team_name', models.CharField(blank=True, max_length=255)),
                ('away_team_logo', models.URLField(blank=True, max_length=500)),
                ('score', models.CharField(blank=True, max_length=32)),
                ('live_minute', models.IntegerField(blank=True, null=True)),
                ('live_minute_label', models.CharField(blank=True, max_length=32)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
                'indexes': [models.Index(fields=['sync_scope', 'starts_at'], name='game_footba_sync_sc_c4a723_idx'), models.Index(fields=['time_status'], name='game_footba_time_st_354419_idx'), models.Index(fields=['league_id'], name='game_footba_league__941214_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_football_match_provider_external_id')],
            },
        ),
    ]
