# Generated by Django 5.2.17 on 2026-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballmatch',
            name='sync_scope',
            field=models.CharField(choices=[('live', 'Идет'), ('prematch', 'Скоро'), ('finished', 'Завершен')], max_length=16),
        ),
    ]
