# Generated by Django 5.2.17 on 2026-08-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_footballmatch_match_and_seo_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='match',
            new_name='game_match_sync_sc_bc0326_idx',
            old_name='game_footba_sync_sc_c4a723_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='game_match_time_st_c9fe43_idx',
            old_name='game_footba_time_st_354419_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='game_match_league__52bcd1_idx',
            old_name='game_footba_league__941214_idx',
        ),
    ]
