# Generated by Django 5.2.17 on 2026-08-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_normalize_match_entities'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='game_match_league__52bcd1_idx',
        ),
        migrations.RenameIndex(
            model_name='leagueseason',
            new_name='game_league_league__cacd22_idx',
            old_name='game_league_league__71a777_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='game_match_sport_i_bbf1c9_idx',
            old_name='game_match_sport_i_0e55a7_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='game_match_league__0df76a_idx',
            old_name='game_match_league__847db6_idx',
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['league_external_id'], name='game_match_league__18b595_idx'),
        ),
    ]
