# Generated by Django 5.2.17 on 2026-08-25 23:15

import django.db.models.deletion
from django.db import migrations, models


def migrate_raw_odds(apps, schema_editor):
    Match = apps.get_model("game", "Match")
    MatchOdds = apps.get_model("game", "MatchOdds")

    def to_float(value):
        if value in (None, ""):
            return None
        try:
            return float(value)
        except (TypeError, ValueError):
            return None

    rows = []
    for match in Match.objects.only("id", "raw_data").iterator(chunk_size=1000):
        raw_data = match.raw_data if isinstance(match.raw_data, dict) else {}
        odds = raw_data.get("odds") if isinstance(raw_data.get("odds"), dict) else {}
        if not odds:
            continue
        rows.append(
            MatchOdds(
                match_id=match.id,
                home_win_bet=to_float(odds.get("home_win_bet")),
                x_bet=to_float(odds.get("x_bet")),
                away_win_bet=to_float(odds.get("away_win_bet")),
                goals_over_2_5=to_float(odds.get("goals_over_2_5")),
                goals_under_2_5=to_float(odds.get("goals_under_2_5")),
                fora_1_0=to_float(odds.get("fora_1_0")),
                fora_2_0=to_float(odds.get("fora_2_0")),
                btts_yes=to_float(odds.get("btts_yes")),
                btts_no=to_float(odds.get("btts_no")),
                d_1x=to_float(odds.get("d_1x")),
                d_2x=to_float(odds.get("d_2x")),
                first_time_home_win_bet=to_float(odds.get("first_time_home_win_bet")),
                first_time_x_bet=to_float(odds.get("first_time_x_bet")),
                first_time_away_win_bet=to_float(odds.get("first_time_away_win_bet")),
                totals_all=odds.get("totals_all") if isinstance(odds.get("totals_all"), dict) else {},
            )
        )
        if len(rows) >= 1000:
            MatchOdds.objects.bulk_create(rows, ignore_conflicts=True)
            rows = []
    if rows:
        MatchOdds.objects.bulk_create(rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_prediction_coefficient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_win_bet', models.FloatField(blank=True, null=True)),
                ('x_bet', models.FloatField(blank=True, null=True)),
                ('away_win_bet', models.FloatField(blank=True, null=True)),
                ('goals_over_2_5', models.FloatField(blank=True, null=True)),
                ('goals_under_2_5', models.FloatField(blank=True, null=True)),
                ('fora_1_0', models.FloatField(blank=True, null=True)),
                ('fora_2_0', models.FloatField(blank=True, null=True)),
                ('btts_yes', models.FloatField(blank=True, null=True)),
                ('btts_no', models.FloatField(blank=True, null=True)),
                ('d_1x', models.FloatField(blank=True, null=True)),
                ('d_2x', models.FloatField(blank=True, null=True)),
                ('first_time_home_win_bet', models.FloatField(blank=True, null=True)),
                ('first_time_x_bet', models.FloatField(blank=True, null=True)),
                ('first_time_away_win_bet', models.FloatField(blank=True, null=True)),
                ('totals_all', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Коэффициенты',
                'verbose_name_plural': 'Коэффициенты',
            },
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='game_match_league__18b595_idx',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_external_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_logo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_name_en',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_external_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_logo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_name_en',
        ),
        migrations.RemoveField(
            model_name='match',
            name='league_country',
        ),
        migrations.RemoveField(
            model_name='match',
            name='league_country_en',
        ),
        migrations.RemoveField(
            model_name='match',
            name='league_external_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='league_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='league_name_en',
        ),
        migrations.RemoveField(
            model_name='match',
            name='sport_code',
        ),
        migrations.RemoveField(
            model_name='match',
            name='sport_external_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='venue_external_id',
        ),
        migrations.AddField(
            model_name='matchodds',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='game.match'),
        ),
        migrations.RunPython(migrate_raw_odds, noop_reverse),
        migrations.AddIndex(
            model_name='matchodds',
            index=models.Index(fields=['home_win_bet', 'x_bet', 'away_win_bet'], name='game_matcho_home_wi_10179f_idx'),
        ),
    ]
