# Generated by Django 5.2.17 on 2026-08-25 23:35

from django.db import migrations, models


DIRECT_ODDS_KEYS = {
    "home_win_bet",
    "x_bet",
    "away_win_bet",
    "goals_over_2_5",
    "goals_under_2_5",
    "fora_1_0",
    "fora_2_0",
    "btts_yes",
    "btts_no",
    "d_1x",
    "d_2x",
    "first_time_home_win_bet",
    "first_time_x_bet",
    "first_time_away_win_bet",
}

GROUP_ALIASES = {
    "totals_all": ("totals_all", "totals", "total_goals", "goals_totals"),
    "double_chance_all": ("double_chance_all", "double_chance", "double_chances"),
    "handicaps_all": ("handicaps_all", "handicaps", "fora_all", "spreads"),
    "btts_all": ("btts_all", "both_teams_to_score", "both_score"),
    "team_totals_all": ("team_totals_all", "team_totals", "individual_totals"),
    "first_half_totals_all": ("first_half_totals_all", "first_half_totals"),
    "first_half_handicaps_all": ("first_half_handicaps_all", "first_half_handicaps"),
    "half_time_full_time_all": ("half_time_full_time_all", "ht_ft", "halftime_fulltime"),
    "exact_score_all": ("exact_score_all", "correct_score", "exact_score"),
}


def _first_dict(payload, aliases):
    for alias in aliases:
        value = payload.get(alias)
        if isinstance(value, dict):
            return value
    return {}


def populate_extended_odds(apps, schema_editor):
    MatchOdds = apps.get_model("game", "MatchOdds")

    for odds in MatchOdds.objects.select_related("match").iterator(chunk_size=500):
        payload = {}
        match_raw = odds.match.raw_data if isinstance(odds.match.raw_data, dict) else {}
        raw_odds = match_raw.get("odds")
        if isinstance(raw_odds, dict):
            payload = raw_odds

        if not payload:
            continue

        used_keys = set(DIRECT_ODDS_KEYS)
        odds.raw_data = payload
        for field, aliases in GROUP_ALIASES.items():
            setattr(odds, field, _first_dict(payload, aliases))
            used_keys.update(aliases)
        odds.extra_markets = {
            key: value
            for key, value in payload.items()
            if key not in used_keys and isinstance(value, (dict, list))
        }
        odds.save(
            update_fields=[
                "raw_data",
                "totals_all",
                "double_chance_all",
                "handicaps_all",
                "btts_all",
                "team_totals_all",
                "first_half_totals_all",
                "first_half_handicaps_all",
                "half_time_full_time_all",
                "exact_score_all",
                "extra_markets",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_matchodds_remove_match_game_match_league__18b595_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchodds',
            name='btts_all',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='double_chance_all',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='exact_score_all',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='extra_markets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='first_half_handicaps_all',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='first_half_totals_all',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='half_time_full_time_all',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='handicaps_all',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='team_totals_all',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(populate_extended_odds, migrations.RunPython.noop),
    ]
