# Generated by Django 5.2.17 on 2026-09-06 12:16

from django.db import migrations, models


def backfill_numeric_sync_scopes(apps, schema_editor):
    Match = apps.get_model("game", "Match")
    status_to_scope = {
        "0": "prematch",
        "1": "live",
        "2": "live",
        "3": "finished",
        "4": "postponed",
        "5": "canceled",
        "6": "forfeit",
        "7": "interrupted",
        "8": "abandoned",
    }
    for time_status, sync_scope in status_to_scope.items():
        Match.objects.filter(time_status=time_status).update(sync_scope=sync_scope)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_prediction_coupon_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='sync_scope',
            field=models.CharField(choices=[('live', 'Идет'), ('prematch', 'Скоро'), ('finished', 'Завершен'), ('postponed', 'Отложен'), ('canceled', 'Отменен'), ('forfeit', 'Техническая победа'), ('interrupted', 'Прерван'), ('abandoned', 'Прерван окончательно')], max_length=16),
        ),
        migrations.RunPython(backfill_numeric_sync_scopes, migrations.RunPython.noop),
    ]
