# Generated by Django 5.2.17 on 2026-09-10 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_match_sync_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_type', models.CharField(choices=[('sport', 'Для спорта'), ('express', 'Для экспресса')], db_index=True, default='sport', max_length=16, verbose_name='Тип обложки')),
                ('image', models.ImageField(upload_to='prediction_covers/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Название')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_cover_images', to='game.sport', verbose_name='Спорт')),
            ],
            options={
                'verbose_name': 'Обложка прогноза',
                'verbose_name_plural': 'Обложки прогнозов',
                'ordering': ['cover_type', 'sport__name_ru', 'sport__name', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='predictioncoupon',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_coupons', to='game.predictioncoverimage', verbose_name='Обложка'),
        ),
        migrations.AddIndex(
            model_name='predictioncoverimage',
            index=models.Index(fields=['cover_type', 'sport', 'is_active'], name='game_predic_cover_t_8e1e39_idx'),
        ),
    ]
