# Generated by Django 5.2.18 on 2026-10-07 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0031_prediction_outcome_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionCouponResultChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("win", "Выигрыш"),
                            ("lose", "Проигрыш"),
                            ("refund", "Возврат"),
                        ],
                        max_length=16,
                        verbose_name="Был результат",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("win", "Выигрыш"),
                            ("lose", "Проигрыш"),
                            ("refund", "Возврат"),
                        ],
                        max_length=16,
                        verbose_name="Стал результат",
                    ),
                ),
                (
                    "previous_payout",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Была выплата"
                    ),
                ),
                (
                    "new_payout",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Стала выплата"
                    ),
                ),
                (
                    "author_coins",
                    models.BigIntegerField(default=0, verbose_name="Коины автору"),
                ),
                (
                    "uncollected_coins",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Сколько коинов не удалось забрать у автора и копировщиков из-за нехватки баланса.",
                        verbose_name="Не удалось списать",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auto", "Автоматический расчёт"),
                            ("resettle", "Перерасчёт"),
                            ("admin", "Правка в админке"),
                        ],
                        max_length=16,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Изменил",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_changes",
                        to="game.predictioncoupon",
                        verbose_name="Прогноз",
                    ),
                ),
            ],
            options={
                "verbose_name": "Смена результата прогноза",
                "verbose_name_plural": "История результатов прогноза",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
