# Generated by Django 5.2.18 on 2026-10-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0032_predictioncouponresultchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictioncoupon",
            name="mobile_card_background",
            field=models.CharField(
                blank=True,
                help_text="Путь к картинке из static, выбирается автоматически. Очистите, чтобы выбрать заново.",
                max_length=255,
                verbose_name="Фон карточки в мобильном слайдере",
            ),
        ),
    ]
