# Generated by Codex on 2026-10-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0034_prediction_mobile_card_background"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictioncoupon",
            name="mobile_card_background",
        ),
        migrations.RemoveField(
            model_name="prediction",
            name="mobile_card_background",
        ),
    ]
