# Generated by Codex on 2026-10-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0036_prediction_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictioncoverimage",
            name="mobile_image",
            field=models.ImageField(
                blank=True,
                upload_to="prediction_covers/mobile/",
                verbose_name="Компактное изображение для телефона",
            ),
        ),
        migrations.AlterField(
            model_name="predictioncoverimage",
            name="image",
            field=models.ImageField(
                upload_to="prediction_covers/",
                verbose_name="Изображение для компьютера",
            ),
        ),
    ]
