# Generated by Django 5.2.17 on 2026-08-26 19:36

from django.db import migrations, models


def fill_existing_telegram_links(apps, schema_editor):
    AnalystProfile = apps.get_model("cabinet", "AnalystProfile")
    for profile in AnalystProfile.objects.select_related("user").all():
        username = profile.user.username if profile.user_id else f"expert_{profile.pk}"
        handle = "".join(char if char.isalnum() else "_" for char in username.lower()).strip("_")
        handle = handle[:28] or f"expert_{profile.pk}"
        changed_fields = []
        if not profile.telegram_account:
            profile.telegram_account = f"https://t.me/{handle}"
            changed_fields.append("telegram_account")
        if not profile.telegram_channel:
            profile.telegram_channel = f"https://t.me/{handle}_tips"
            changed_fields.append("telegram_channel")
        if changed_fields:
            profile.save(update_fields=changed_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_alter_user_options_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=160, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='analystprofile',
            name='telegram_account',
            field=models.CharField(default='', max_length=160, verbose_name='Telegram аккаунт'),
        ),
        migrations.AddField(
            model_name='analystprofile',
            name='telegram_channel',
            field=models.CharField(default='', max_length=160, verbose_name='Telegram канал'),
        ),
        migrations.AddField(
            model_name='analystprofile',
            name='threads',
            field=models.CharField(blank=True, max_length=160, verbose_name='Threads'),
        ),
        migrations.AddField(
            model_name='analystprofile',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, verbose_name='YouTube канал'),
        ),
        migrations.RunPython(fill_existing_telegram_links, migrations.RunPython.noop),
    ]
