# Generated by Django 5.2.17 on 2026-08-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_analystprofile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='analystprofile',
            name='tiktok',
            field=models.CharField(blank=True, max_length=160, verbose_name='TikTok'),
        ),
    ]
