# Generated by Django 5.2.17 on 2026-09-05 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0022_analystprofile_verification_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystprofile',
            name='trust_index',
            field=models.DecimalField(db_index=True, decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Индекс доверия'),
        ),
        migrations.AddField(
            model_name='analystprofile',
            name='trust_index_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Индекс доверия обновлён'),
        ),
    ]
