# Generated by Django 5.2.17 on 2026-09-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0025_referralvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystprofile',
            name='x',
            field=models.CharField(blank=True, max_length=160, verbose_name='X'),
        ),
    ]
