# Generated by Django 5.2.17 on 2026-09-29 13:05

from decimal import Decimal, ROUND_FLOOR

from django.db import migrations, models


def migrate_vip_plan_prices_to_rub(apps, schema_editor):
    VipPlan = apps.get_model("cabinet", "VipPlan")
    CoinSettings = apps.get_model("wallets", "CoinSettings")

    settings = CoinSettings.objects.order_by("pk").first()
    coin_price_rub = getattr(settings, "coin_price_rub", None) or Decimal("1.00")
    coin_price_rub = Decimal(str(coin_price_rub))

    for plan in VipPlan.objects.filter(price_rub=0, price_coins__gt=0):
        plan.price_rub = (Decimal(plan.price_coins) * coin_price_rub).quantize(
            Decimal("0.01"),
            rounding=ROUND_FLOOR,
        )
        plan.save(update_fields=["price_rub"])


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0051_remove_analystprofile_avatar'),
        ('wallets', '0010_fix_legacy_rub_coin_cutover'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipplan',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость, ₽'),
        ),
        migrations.RunPython(migrate_vip_plan_prices_to_rub, migrations.RunPython.noop),
    ]
