# Generated by Django 5.2.17 on 2026-09-29 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0052_vipplan_price_rub'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystPaidSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('capper_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Доход каппера')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Срок, дней')),
                ('starts_at', models.DateTimeField(verbose_name='Начало периода')),
                ('expires_at', models.DateTimeField(verbose_name='Окончание периода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_prediction_sales', to=settings.AUTH_USER_MODEL, verbose_name='Аналитик')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cabinet.analystpaidplan', verbose_name='Тариф')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_prediction_payments', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cabinet.analystpaidsubscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Платёж за платные прогнозы',
                'verbose_name_plural': 'Платежи за платные прогнозы',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['subscriber', 'created_at'], name='paid_pay_subscriber_idx'), models.Index(fields=['analyst', 'created_at'], name='paid_pay_analyst_idx'), models.Index(fields=['subscription', 'created_at'], name='paid_pay_subscription_idx')],
            },
        ),
    ]
