# Generated by Django 5.2.17 on 2026-10-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0059_user_mobile_quick_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralbonussettings',
            name='max_visible_reward_text',
            field=models.CharField(default='До 1000 коинов', max_length=120, verbose_name='Текст максимальной награды'),
        ),
    ]
