# Generated by Django 5.2.17 on 2026-10-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0060_alter_referralbonussettings_max_visible_reward_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservipsubscription',
            name='source',
            field=models.CharField(choices=[('purchase', 'Покупка'), ('admin', 'Администратор'), ('roulette', 'Рулетка'), ('tournament', 'Турнир'), ('bonus', 'Бонус'), ('legacy_admin', 'Перенос старого VIP')], default='purchase', max_length=16, verbose_name='Источник'),
        ),
    ]
