# Generated by Django 5.2.18 on 2026-10-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0062_roulettesettings_free_prediction_stake"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_ip",
            field=models.GenericIPAddressField(
                blank=True, db_index=True, null=True, verbose_name="IP регистрации"
            ),
        ),
    ]
