# Generated by Django 5.2.18 on 2026-10-07 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0063_user_registration_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Аккаунт обезличен: личные данные стёрты, финансовая история сохранена.",
                null=True,
                verbose_name="Аккаунт удалён",
            ),
        ),
        migrations.AlterField(
            model_name="analystpaidsubscription",
            name="analyst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paid_prediction_subscribers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Аналитик",
            ),
        ),
        migrations.AlterField(
            model_name="analystpaidsubscription",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paid_prediction_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчик",
            ),
        ),
        migrations.AlterField(
            model_name="analystpaidsubscriptionpayment",
            name="analyst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paid_prediction_sales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Аналитик",
            ),
        ),
        migrations.AlterField(
            model_name="analystpaidsubscriptionpayment",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paid_prediction_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчик",
            ),
        ),
    ]
