# Generated by Django 5.2.18 on 2026-10-07 15:12

from datetime import datetime, timedelta, timezone as datetime_timezone

from django.db import migrations


def keep_flagged_vips(apps, schema_editor):
    # The flag was converted to subscriptions in 0041; repeat it for flags set later
    # so removing the field cannot take VIP away from anyone.
    AnalystProfile = apps.get_model("cabinet", "AnalystProfile")
    UserVipSubscription = apps.get_model("cabinet", "UserVipSubscription")
    ends_at = datetime(2099, 12, 31, 23, 59, 59, tzinfo=datetime_timezone.utc)
    for profile in AnalystProfile.objects.filter(is_vip=True).select_related("user"):
        starts_at = profile.vip_activated_at or profile.updated_at or profile.user.date_joined
        UserVipSubscription.objects.get_or_create(
            user_id=profile.user_id,
            source="legacy_admin",
            defaults={
                "plan_id": None,
                "starts_at": starts_at,
                "ends_at": max(ends_at, starts_at + timedelta(days=1)),
                "duration_days": max(1, (ends_at - starts_at).days),
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0064_user_deleted_at_and_more"),
    ]

    operations = [
        migrations.RunPython(keep_flagged_vips, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="analystprofile",
            name="is_vip",
        ),
        migrations.RemoveField(
            model_name="analystprofile",
            name="vip_activated_at",
        ),
    ]
