# Generated by Django 5.2.18 on 2026-10-07 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0065_remove_analystprofile_legacy_vip"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analystpaidsubscriptionpayment",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paid_subscription_payment",
                to="payments.payment",
                verbose_name="Оплата у провайдера",
            ),
        ),
        migrations.AddField(
            model_name="uservipsubscription",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vip_subscription",
                to="payments.payment",
                verbose_name="Оплата у провайдера",
            ),
        ),
    ]
