# Generated by Django 5.2.18 on 2026-10-08 15:57

from django.db import migrations, models


def clear_pending_requests(apps, schema_editor):
    # Requests from the old flow waited for an admin. Now the checkmark is given on
    # request, and a date without the checkmark means an admin removed it, so these
    # old dates would block the button for good.
    AnalystProfile = apps.get_model("cabinet", "AnalystProfile")
    AnalystProfile.objects.filter(is_verified=False, verification_requested_at__isnull=False).update(
        verification_requested_at=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0066_payment_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analystprofile",
            name="verification_requested_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Когда каппер получил галочку кнопкой в настройках. Если снять «Проверен» и оставить эту дату, кнопка у каппера больше не появится. Очистите дату, чтобы разрешить снова.",
                null=True,
                verbose_name="Галочка запрошена",
            ),
        ),
        migrations.RunPython(clear_pending_requests, migrations.RunPython.noop),
    ]
