# Generated by Django 5.2.18 on 2026-10-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0067_verification_on_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rouletteprizecondition",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("all_users", "Все пользователи"),
                    ("readers_only", "Только обычные пользователи"),
                    ("analysts_only", "Только капперы"),
                    ("without_vip", "Только без VIP"),
                    ("vip_only", "Только с VIP"),
                    ("min_account_age_days", "Минимальный возраст аккаунта"),
                    ("min_activity_count", "Минимальная активность"),
                ],
                max_length=32,
                verbose_name="Условие",
            ),
        ),
    ]
