# Generated by Django 5.2.18 on 2026-10-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0068_roulette_vip_only_condition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analystprofile",
            name="cover_image",
        ),
    ]
