# Generated by Django 5.2.17 on 2026-08-27 13:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def copy_existing_telegram_links(apps, schema_editor):
    NotificationPreference = apps.get_model("notifications", "NotificationPreference")
    TelegramAccount = apps.get_model("notifications", "TelegramAccount")
    now = django.utils.timezone.now()

    for preference in NotificationPreference.objects.exclude(telegram_chat_id=""):
        chat_id = str(preference.telegram_chat_id or "").strip()
        if not chat_id:
            continue
        TelegramAccount.objects.filter(chat_id=chat_id).exclude(
            user_id=preference.user_id
        ).delete()
        TelegramAccount.objects.update_or_create(
            user_id=preference.user_id,
            defaults={
                "chat_id": chat_id,
                "username": str(preference.telegram_username or "")[:80],
                "connected_at": preference.telegram_connected_at or now,
                "last_seen_at": now,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_telegram_linking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Telegram chat id')),
                ('username', models.CharField(blank=True, max_length=80, verbose_name='Telegram username')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='Имя в Telegram')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='Фамилия в Telegram')),
                ('language_code', models.CharField(blank=True, max_length=12, verbose_name='Язык Telegram')),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Подключён')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram-аккаунт',
                'verbose_name_plural': 'Telegram-аккаунты',
                'ordering': ('-connected_at',),
            },
        ),
        migrations.RunPython(copy_existing_telegram_links, migrations.RunPython.noop),
    ]
