# Generated by Django 5.2.17 on 2026-10-01 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Max


SECTION_BY_KIND = {
    "prediction_like": "predictions",
    "prediction_favorite": "predictions",
    "own_coupon_settled": "predictions",
    "copybetting": "copybetting",
    "new_follower": "followers",
    "paid_subscription": "earnings",
    "achievement": "achievements",
    "bonus_daily_task": "bonus_tasks",
    "bonus_streak": "bonus_levels",
    "bonus_level": "bonus_levels",
    "bonus_roulette": "bonuses",
    "bonus_referral": "referrals",
    "new_prediction": "following",
    "requested_match_prediction": "following",
    "favorite_settled": "following",
    "match_prediction": "matches",
    "match_reminder": "matches",
    "tournament_started": "tournaments",
    "tournament_finished": "tournaments",
}


def backfill_section_states(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    NotificationSectionState = apps.get_model("notifications", "NotificationSectionState")

    folded = {}
    rows = (
        Notification.objects.filter(
            show_in_app=True,
            is_read=False,
            kind__in=SECTION_BY_KIND.keys(),
        )
        .values("recipient_id", "kind")
        .annotate(unread_count=Count("id"), latest_id=Max("id"))
    )
    for row in rows:
        section = SECTION_BY_KIND[row["kind"]]
        key = (row["recipient_id"], section)
        current = folded.setdefault(
            key,
            {
                "unread_count": 0,
                "latest_id": None,
            },
        )
        current["unread_count"] += row["unread_count"]
        if current["latest_id"] is None or row["latest_id"] > current["latest_id"]:
            current["latest_id"] = row["latest_id"]

    NotificationSectionState.objects.bulk_create(
        [
            NotificationSectionState(
                user_id=user_id,
                section=section,
                unread_count=payload["unread_count"],
                latest_notification_id=payload["latest_id"],
            )
            for (user_id, section), payload in folded.items()
        ],
        batch_size=1000,
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_admin_campaign_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('predictions', 'Мои прогнозы'), ('copybetting', 'Копибеттинг'), ('followers', 'Подписчики'), ('earnings', 'Доходы'), ('achievements', 'Достижения'), ('bonus_tasks', 'Ежедневные задания'), ('bonus_levels', 'Уровни'), ('bonuses', 'Бонусы'), ('referrals', 'Рефералы'), ('following', 'Подписки'), ('matches', 'Матчи'), ('tournaments', 'Турниры')], max_length=32, verbose_name='Раздел')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='Непрочитано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('latest_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notifications.notification', verbose_name='Последнее уведомление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_section_states', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Состояние уведомлений раздела',
                'verbose_name_plural': 'Состояния уведомлений разделов',
                'indexes': [models.Index(fields=['user', 'unread_count'], name='notif_section_unread_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'section'), name='notif_section_state_unique')],
            },
        ),
        migrations.RunPython(backfill_section_states, migrations.RunPython.noop),
    ]
