# Generated by Django 5.2.18 on 2026-10-07 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_notificationsectionstate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="delivery_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Неудачных попыток доставки"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="next_delivery_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Следующая попытка доставки"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(
                    ("email_processed_at__isnull", True),
                    ("telegram_processed_at__isnull", True),
                    _connector="OR",
                ),
                fields=["next_delivery_at", "created_at"],
                name="notif_delivery_pending_idx",
            ),
        ),
    ]
